%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Admin\Documents\MATLAB\CMSC828V\Project2Data\MovRankData.csv
%
% Auto-generated by MATLAB on 2021-11-05 13:13:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["UserID", "HomeAlone", "TheLionKing", "ThePrincessBride", "Titanic", "BeautyAndTheBeast", "Cinderella", "Shrek", "ForrestGump", "Aladdin", "FerrisBuellersDayOff", "FindingNemo", "HarryPotterAndTheSorcerersStone", "BackToTheFuture", "UP", "TheBreakfastClub", "TheTrumanShow", "AvengersEndgame", "TheIncredibles", "Coraline", "Elf"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "UserID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "UserID", "EmptyFieldRule", "auto");

% Import the data
MovRankData = readtable("C:\Users\Admin\Documents\MATLAB\CMSC828V\Project2Data\MovRankData.csv", opts);


%% Clear temporary variables
clear opts